Update Build SukiSU Ultra.yml

diff --git a/.github/workflows/Build SukiSU Ultra.yml b/.github/workflows/Build SukiSU Ultra.yml
--- a/.github/workflows/Build SukiSU Ultra.yml
+++ b/.github/workflows/Build SukiSU Ultra.yml
@@ -154,7 +154,6 @@ jobs:
             build-essential flex bison libssl-dev \
             libncurses-dev liblz4-tool zlib1g-dev \
             libxml2-utils rsync unzip
-          
           echo "✅ 依赖安装完成"
 
       - name: 📥 Restore ccache (恢复 ccache 缓存)
@@ -209,18 +208,18 @@ jobs:
           
       - name: ⚙️ Set SuKiSU Ultra (设置SuKiSU Ultra)
         run: |
-            mkdir -p kernel_workspace/kernel_platform
-              cd kernel_workspace/kernel_platform
-              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/setup.sh" | bash -s susfs-main
-              cd KernelSU
-              cp "${GITHUB_WORKSPACE}/.github/workflows/setup.bin" ./
-              chmod +x setup.bin
-              if [ ! -f "kernel/Makefile" ]; then
-                echo "::error ::kernel/Makefile"
-                ls -la
-                exit 1
-              fi
-              ./setup.bin
+          mkdir -p kernel_workspace/kernel_platform
+          cd kernel_workspace/kernel_platform
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/setup.sh" | bash -s susfs-main
+          cd KernelSU
+          cp "${GITHUB_WORKSPACE}/script/setup.bin" ./
+          chmod +x setup.bin
+          if [ ! -f "kernel/Makefile" ]; then
+            echo "::error ::kernel/Makefile"
+            ls -la
+            exit 1
+          fi
+          ./setup.bin
           
       - name: 🔧 Set up SUSFS (配置 SUSFS)
         run: |
